language: c
 
install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console
  - mozroots --import --sync
 
script:
  - xbuild ./HelperSharp.sln /property:"Configuration=Debug;Platform=Any CPU"
  - nunit-console ./HelperSharp.UnitTests/bin/Debug/HelperSharp.UnitTests.dll
